**Requirements (install locally):**
```bash
pip install psycopg2-binary SQLAlchemy geoalchemy2 geopandas shapely pyproj fiona rasterio matplotlib flask
```

**Conda environment (optional):**
```bash
conda create -n postgis python=3.10
conda activate postgis
conda install -c conda-forge psycopg2 sqlalchemy geoalchemy2 geopandas shapely pyproj fiona rasterio matplotlib flask
```

In [28]:
# 1) Connect to PostGIS
from sqlalchemy import create_engine, text
from sqlalchemy.pool import NullPool

PG_USER = "sakdahomhuan"
PG_PASS = "1234"
PG_HOST = "localhost"
PG_PORT = 5432
PG_DB   = "geo377"

engine = create_engine(
    f"postgresql+psycopg2://{PG_USER}:{PG_PASS}@{PG_HOST}:{PG_PORT}/{PG_DB}",
    poolclass=NullPool, future=True
)

with engine.begin() as conn:
    version = conn.execute(text("SELECT postgis_full_version();")).scalar_one()
version

'POSTGIS="3.6.0 0" [EXTENSION] PGSQL="140" GEOS="3.14.0-CAPI-1.20.4" PROJ="9.6.2 NETWORK_ENABLED=OFF URL_ENDPOINT=https://cdn.proj.org USER_WRITABLE_DIRECTORY=/Users/sakdahomhuan/Library/Application Support/proj DATABASE_PATH=/opt/homebrew/Cellar/proj/9.6.2/share/proj/proj.db" (compiled against PROJ 9.6.2) GDAL="GDAL 3.11.3 "Eganville", released 2025/07/12" LIBXML="2.13.8" LIBJSON="0.18" LIBPROTOBUF="1.5.2" WAGYU="0.5.0 (Internal)" TOPOLOGY RASTER'

In [29]:
# 2) Initialize schema
sql = open("python_17_postgis_setup.sql", "r", encoding="utf-8").read()
with engine.begin() as conn:
    conn.exec_driver_sql(sql)
print("PostGIS workshop schema initialized.")

PostGIS workshop schema initialized.

In [30]:
# 3) Checks counts and SRID
from pandas import DataFrame
from sqlalchemy import text
with engine.begin() as conn:
    rs = conn.execute(text("""

        SELECT 'hospital' AS tbl, COUNT(*) AS n, MIN(ST_SRID(geom)) AS srid FROM public.cm_hospital_4326

        UNION ALL

        SELECT 'districts' AS tbl, COUNT(*) AS n, MIN(ST_SRID(geom)) AS srid FROM workshop.districts;

    """))
    df = DataFrame(rs.fetchall(), columns=rs.keys())
df

         tbl   n  srid
0   hospital  59  4326
1  districts   1  4326

In [31]:
# 4) Loads data from PostGIS to GeoDataFrame
import geopandas as gpd
from shapely.geometry import Point

gpoi = gpd.read_postgis(
    "SELECT id, name, geom FROM public.cm_hospital_4326",
    engine, geom_col="geom"
)
display(gpoi.head())

   id                       name                       geom
0   1  โรงพยาบาลกรุงเทพเชียงใหม่  POINT (99.02642 18.78853)
1   2         โรงพยาบาลกองบิน 41  POINT (98.97138 18.77809)
2   3            โรงพยาบาลกาวิละ  POINT (99.01483 18.77794)
3   4        โรงพยาบาลค่ายกาวิละ  POINT (99.01488 18.77793)
4   5            โรงพยาบาลจอมทอง  POINT (98.67392 18.40632)

In [32]:
# 5) Spatial query: find POIs within districts
import pandas as pd
from sqlalchemy import text

q1 = text("""

SELECT p.id, p.name,

       ST_AsText(p.geom) AS wkt,

       ST_Within(p.geom, d.geom) AS inside_district

FROM public.cm_hospital_4326 p

JOIN workshop.districts d

  ON p.geom && d.geom AND ST_Intersects(p.geom, d.geom);

""")
with engine.begin() as conn:
    df = pd.DataFrame(conn.execute(q1).fetchall(), columns=["id","name","wkt","inside_district"])
df

,id,name,wkt,inside_district
0,6,โรงพยาบาลช้างเผือก,POINT(98.98704276000007 18.798882440000057),True
1,10,โรงพยาบาลเชียงใหม่ราม,POINT(98.97775677000004 18.795082310000055),True
2,18,โรงพยาบาลเด็กเชียงใหม่ราม,POINT(98.97761676000005 18.794845690000045),True
3,23,โรงพยาบาลเทพปัญญา2,POINT(98.98704010000006 18.79892756000004),True

In [33]:
# 6) Spatial query: KNN (K-Nearest Neighbor) search จาก hospital แต่ละแห่ง หา hospital ที่ใกล้ที่สุด 1 แห่ง
q2 = text("""

SELECT p.id, p.name,

       f.id  AS nearest_id,

       ST_Distance(p.geom::geography, f.geom::geography) AS meters

FROM public.cm_hospital_4326 p

CROSS JOIN LATERAL (

  SELECT id, geom FROM public.cm_hospital_4326 f

  WHERE f.id <> p.id

  ORDER BY f.geom <-> p.geom

  LIMIT 1

) f;

""")

with engine.begin() as conn:

    knn = conn.execute(q2).fetchall()

knn[:5]

[(1, 'โรงพยาบาลกรุงเทพเชียงใหม่', 20, 819.33034467),
 (2, 'โรงพยาบาลกองบิน 41', 49, 841.44439205),
 (3, 'โรงพยาบาลกาวิละ', 4, 5.00198492),
 (4, 'โรงพยาบาลค่ายกาวิละ', 3, 5.00198492),
 (5, 'โรงพยาบาลจอมทอง', 16, 13768.62303711)]

In [34]:
# 7) Spatial query: aggregate hospital counts by district
q3 = text("""

SELECT d.name, COUNT(p.*) AS cnt

FROM workshop.districts d

LEFT JOIN public.cm_hospital_4326 p

  ON d.geom && p.geom AND ST_Intersects(d.geom, p.geom)

GROUP BY d.name ORDER BY cnt DESC;

""")

import pandas as pd

with engine.begin() as conn:

    agg = pd.DataFrame(conn.execute(q3).fetchall(), columns=["district","count"])

agg

        district  count
0  Demo District      4

In [39]:
# 8) Export query result as GeoJSON
from sqlalchemy import text
q_geojson = text("""

SELECT jsonb_build_object(

  'type','FeatureCollection',

  'features', jsonb_agg(jsonb_build_object(

     'type','Feature',

     'properties', jsonb_build_object('id', id, 'name', name),

     'geometry', ST_AsGeoJSON(geom)::jsonb

  ))

) AS fc

FROM public.cm_hospital_4326;

""")

with engine.begin() as conn:

    fc = conn.execute(q_geojson).scalar_one()

fc

{'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.02642032, 18.78853112]},
   'properties': {'id': 1, 'name': 'โรงพยาบาลกรุงเทพเชียงใหม่'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.97138436, 18.77808769]},
   'properties': {'id': 2, 'name': 'โรงพยาบาลกองบิน 41'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.01483439, 18.77794254]},
   'properties': {'id': 3, 'name': 'โรงพยาบาลกาวิละ'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.01487874, 18.77792649]},
   'properties': {'id': 4, 'name': 'โรงพยาบาลค่ายกาวิละ'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.67391898, 18.40632131]},
   'properties': {'id': 5, 'name': 'โรงพยาบาลจอมทอง'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.98704276, 18.79888244]},
   'properties': {'id': 6, 'name': 'โรงพยาบาลช้างเผือก'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.97516318, 19.40295128]},
   'properties': {'id': 7, 'name': 'โรงพยาบาลเชียงดาว'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.97234376, 18.76062113]},
   'properties': {'id': 8, 'name': 'โรงพยาบาลเชียงใหม่ใกล้หมอ'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.9884352, 18.78018104]},
   'properties': {'id': 9, 'name': 'โรงพยาบาลเชียงใหม่เมดิคอลเซ็นเตอร์'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.97775677, 18.79508231]},
   'properties': {'id': 10, 'name': 'โรงพยาบาลเชียงใหม่ราม'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.98150745, 18.81067293]},
   'properties': {'id': 11, 'name': 'โรงพยาบาลเชียงใหม่ฮอสพิทอล'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.13685897, 19.70564367]},
   'properties': {'id': 12, 'name': 'โรงพยาบาลไชยปราการ'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.99832212, 18.77312065]},
   'properties': {'id': 13, 'name': 'โรงพยาบาลเซ็นทรัลเชียงใหม่เมโมเรียล'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.69090941, 17.95016802]},
   'properties': {'id': 14, 'name': 'โรงพยาบาลดอยเต่า'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.12840019, 18.86899463]},
   'properties': {'id': 15, 'name': 'โรงพยาบาลดอยสะเก็ด'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.78056305, 18.47783746]},
   'properties': {'id': 16, 'name': 'โรงพยาบาลดอยหล่อ'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.9450781, 18.91060335]},
   'properties': {'id': 17, 'name': 'โรงพยาบาลดารารัศมี'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.97761676, 18.79484569]},
   'properties': {'id': 18, 'name': 'โรงพยาบาลเด็กเชียงใหม่ราม'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.99085585, 18.81138711]},
   'properties': {'id': 19, 'name': 'โรงพยาบาลตาเซนต์ปีเตอร์'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.03384176, 18.78633402]},
   'properties': {'id': 20, 'name': 'โรงพยาบาลตำบลหนองป่าครั่ง'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.02482468, 18.79704572]},
   'properties': {'id': 21, 'name': 'โรงพยาบาลทันตกรรมเอเซียฟอร์จูน'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.01147561, 18.81024424]},
   'properties': {'id': 22, 'name': 'โรงพยาบาลเทพปัญญา'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.9870401, 18.79892756]},
   'properties': {'id': 23, 'name': 'โรงพยาบาลเทพปัญญา2'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.36515554, 18.49812409]},
   'properties': {'id': 24,
    'name': 'โรงพยาบาลเทพรัตนเวชชานุกูลเฉลิมพระเกียรติ 60 พรรษา'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.00176634, 18.78848259]},
   'properties': {'id': 25, 'name': 'โรงพยาบาลเทศบาลนครเชียงใหม่'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.94041608, 19.01711238]},
   'properties': {'id': 26, 'name': 'โรงพยาบาลธัญญารักษ์เชียงใหม่'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.9680547, 18.85173638]},
   'properties': {'id': 27, 'name': 'โรงพยาบาลนครพิงค์'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.99734605, 18.78154876]},
   'properties': {'id': 28, 'name': 'โรงพยาบาลนครพิงค์ สาขาศรีดอนไชย'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.99734375, 18.7815939]},
   'properties': {'id': 29, 'name': 'โรงพยาบาลนครพิงค์สาขาศรีดอนไชย'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.97822769, 18.7719334]},
   'properties': {'id': 30,
    'name': 'โรงพยาบาลบรรเทาทุกข์โบราณภาคเหนือชีวกโกมารภัจจ์'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.96957309, 18.78972775]},
   'properties': {'id': 31, 'name': 'โรงพยาบาลประสาทเชียงใหม่'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.2063716, 19.91361029]},
   'properties': {'id': 32, 'name': 'โรงพยาบาลฝาง'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.19989884, 19.36794696]},
   'properties': {'id': 33, 'name': 'โรงพยาบาลพร้าว'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.97432122, 18.78952924]},
   'properties': {'id': 34, 'name': 'โรงพยาบาลมหาราชนครเชียงใหม่'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.01082765, 18.7982293]},
   'properties': {'id': 35, 'name': 'โรงพยาบาลแมคคอร์มิค'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.98660615, 18.72868991]},
   'properties': {'id': 36, 'name': 'โรงพยาบาลแมคเคน'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.96017762, 19.13767216]},
   'properties': {'id': 37, 'name': 'โรงพยาบาลแม่แตง'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.77411726, 18.61586806]},
   'properties': {'id': 38, 'name': 'โรงพยาบาลแม่วาง'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.221643, 18.74459224]},
   'properties': {'id': 39, 'name': 'โรงพยาบาลแม่ออน'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.30241634, 20.03874092]},
   'properties': {'id': 40, 'name': 'โรงพยาบาลแม่อาย'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.00417984, 18.76691148]},
   'properties': {'id': 41, 'name': 'โรงพยาบาลราชเวช'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.98149662, 18.81072239]},
   'properties': {'id': 42, 'name': 'โรงพยาบาลโรคฟัน'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.99130361, 18.81260113]},
   'properties': {'id': 43, 'name': 'โรงพยาบาลลานนา'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.99127799, 18.81303911]},
   'properties': {'id': 44, 'name': 'โรงพยาบาลลานนา 2'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.31533968, 19.07743794]},
   'properties': {'id': 45, 'name': 'โรงพยาบาลวัดจันทร์เฉลิมพระเกียรติ'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.31531486, 19.07747647]},
   'properties': {'id': 46,
    'name': 'โรงพยาบาลวัดจันทร์เฉลิมพระเกียรติ 80 พรรษา'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.63515752, 19.56020025]},
   'properties': {'id': 47, 'name': 'โรงพยาบาลเวียงแหง'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.99456402, 18.77331484]},
   'properties': {'id': 48, 'name': 'โรงพยาบาลส่งเสริมสุขภาพเชียงใหม่'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.97906803, 18.7801435]},
   'properties': {'id': 49, 'name': 'โรงพยาบาลสวนปรุง'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.73245, 18.84679812]},
   'properties': {'id': 50, 'name': 'โรงพยาบาลสะเมิง'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.12276508, 18.71589218]},
   'properties': {'id': 51, 'name': 'โรงพยาบาลสันกำแพง'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.99222051, 18.9201971]},
   'properties': {'id': 52, 'name': 'โรงพยาบาลสันทราย'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.88542152, 18.59550692]},
   'properties': {'id': 53, 'name': 'โรงพยาบาลสันป่าตอง'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.0431462, 18.68094114]},
   'properties': {'id': 54, 'name': 'โรงพยาบาลสารภี'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.06142088, 18.70789195]},
   'properties': {'id': 55, 'name': 'โรงพยาบาลสารภีบวรพัฒนา'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.91824127, 18.68323404]},
   'properties': {'id': 56, 'name': 'โรงพยาบาลหางดง'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.36116949, 17.80199232]},
   'properties': {'id': 57, 'name': 'โรงพยาบาลอมก๋อย'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [99.02502118, 18.79739258]},
   'properties': {'id': 58, 'name': 'โรงพยาบาลเอ็มทีอินเตอร์เมด'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [98.61156999, 18.17929884]},
   'properties': {'id': 59, 'name': 'โรงพยาบาลฮอด'}}]}

In [41]:
# show with folium
import folium
m = folium.Map(location=[18.79, 98.98], zoom_start=12)
# folium.GeoJson(fc, name="geojson").add_to(m)
# add marker popup 
for feature in fc['features']:
    coords = feature['geometry']['coordinates'][::-1]  # reverse to (lat, lon)
    name = feature['properties']['name']
    folium.Marker(location=coords, popup=name).add_to(m)

m
#  --- IGNORE ---